# Generated by Django 6.0.4 on 2026-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікування'), ('confirmed', 'Підтверджено'), ('cancelled', 'Відмінено')], default='pending', max_length=20),
        ),
    ]
