# Generated by Django 6.0.4 on 2026-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#667eea', help_text='Колір кімнати у форматі HEX (наприклад: #FF5733)', max_length=7),
        ),
    ]
