# Generated by Django 6.0.4 on 2026-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_room_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#ffffff', help_text='Колір фону сайту', max_length=7)),
                ('primary_color', models.CharField(default='#667eea', help_text='Основний колір (заголовки, кнопки)', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Вторинний колір (градієнти, акценти)', max_length=7)),
                ('text_color', models.CharField(default='#333333', help_text='Колір тексту', max_length=7)),
                ('site_title', models.CharField(default='Система бронювання кімнат', help_text='Назва сайту', max_length=200)),
                ('site_description', models.TextField(default='Зручна система бронювання номерів готелю', help_text='Опис сайту')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайту',
                'verbose_name_plural': 'Настройки сайту',
            },
        ),
    ]
